// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CrudOperation.Entity
{
    public partial class Details
    {
        [Required]
        public int Student_Id { get; set; }
        [Required]
        public string First_Name { get; set; }
        [Required]
        public string Middle_Name { get; set; }
        public string Last_Name { get; set; }
        public string Gender { get; set; }
        public string Course { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Email_Id { get; set; }
        [Required]
        public string Password { get; set; }
        public string Retype_Password { get; set; }
        public bool Is_Deleted { get; set; }
        public DateTime Create_Time_Stamp { get; set; }
        public DateTime Update_Time_Stamp { get; set; }
    }
}